
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5434}/${DB_NAME:hwds}
    username: ${DB_USERNAME:hwds}
    password: ${DB_PASS:1z2x3c4v5b6n7M}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 4
      minimum-idle: 1
  application:
    name: HWDS

  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml


  mail:
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            protocols: TLSv1.2
            trust: smtp.gmail.com
          debug: true



server:
  servlet:
    context-path: /api
  port: 8080

key:
  access: ${KEY_ACCESS:1p+Yz99khoLXqeI28FdElevjMScw0XU1YkNh/WrduLY=}
  refresh: ${KEY_REFRESH:K7iyolWxDkwMNCP/4Kdm5STKRdS7TYl4X3x7ucNYIz8=}

base-url: ${BASE_URL:http://localhost:8080/api}

s3:
  endpoint: ${S3_ENDPOINT}
  region: ${S3_REGION}
  accessKey: ${S3_ACCESS_KEY}
  secretKey: ${S3_SECRET_KEY}
  bucketName: ${S3_BUCKET_NAME}
