<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Confirm Your Registration</title>
</head>
<body>

<h1 style="color: green">Anmeldebestätigung</h1>
<h2>Guten Tag, ${name}!</h2>
<p>Um Ihre Anmeldung zu bestätigen, folgen Sie dem folgenden Link:</p>
<a href="${confirmationLink}">Bestätigen Sie die Registrierung</a>
<p>Vielen Dank, dass Sie sich für unseren Service entschieden haben!</p>

</body>

</html>
